version: "3.3"
services:
  digitransit-ui:
    container_name: "digitransit-ui"
    image: vlaja/digitransit:digitransit_ui
    depends_on:
      - digitransit-otp
  digitransit-otp:
    container_name: "digitransit-otp"
    image: vlaja/digitransit:digitransit_otp
  nginx:
    container_name: "nginx"
    image: nginx:1.15-alpine
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot/
    ports:
      - "80:80"
      - "443:443"
    links:
      - digitransit-ui
      - digitransit-otp
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    container_name: "certbot"
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot/
